use UNIVER;
select FACULTY.FACULTY, GROUPS.PROFESSION,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средн€€ оценка'
from FACULTY inner join GROUPS
on FACULTY.FACULTY = GROUPS.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by FACULTY.FACULTY, GROUPS.PROFESSION