use UNIVER
select FACULTY.FACULTY, GROUPS.PROFESSION,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from FACULTY inner join GROUPS
on FACULTY.FACULTY = GROUPS.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where PROGRESS.SUBJECT like 'БД' or PROGRESS.SUBJECT = 'ОАиП'
group by FACULTY.FACULTY, GROUPS.PROFESSION