use UNIVER
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
From AUDITORIUM,  AUDITORIUM_TYPE 
where AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM_TYPE.AUDITORIUM_TYPE and 
AUDITORIUM_TYPE.AUDITORIUM_TYPENAME Like'%компьютер%' 