use UNIVER;
select FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
From FACULTY, PULPIT, PROFESSION
Where PULPIT.FACULTY=FACULTY.FACULTY and FACULTY.FACULTY=PROFESSION.FACULTY
AND
PROFESSION.PROFESSION_NAME IN(SELECT PROFESSION.PROFESSION_NAME
FROM PROFESSION
WHERE(PROFESSION.PROFESSION_NAME LIKE '%технология%'
or PROFESSION.PROFESSION_NAME LIKE '%технологии%'));
--2

select FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
From FACULTY inner join PULPIT
on PULPIT.FACULTY=FACULTY.FACULTY, PROFESSION
Where PULPIT.FACULTY=FACULTY.FACULTY AND FACULTY.FACULTY=PROFESSION.FACULTY
AND 
PROFESSION.PROFESSION_NAME IN(SELECT PROFESSION.PROFESSION_NAME
FROM PROFESSION
WHERE(PROFESSION.PROFESSION_NAME LIKE '%технология%'
or PROFESSION.PROFESSION_NAME LIKE '%технологии%'));
--3

select FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
From FACULTY inner join PULPIT
on PULPIT.FACULTY=FACULTY.FACULTY
inner join PROFESSION on PROFESSION.FACULTY=FACULTY.FACULTY
WHERE(PROFESSION.PROFESSION_NAME LIKE '%технология%'
or PROFESSION.PROFESSION_NAME LIKE '%технологии%');
--4
Select AUDITORIUM_CAPACITY, AUDITORIUM_TYPE
FROM AUDITORIUM as a
Where AUDITORIUM_CAPACITY=(select top(1) aa.AUDITORIUM_CAPACITY from AUDITORIUM as aa
where aa.AUDITORIUM_TYPE=a.AUDITORIUM_TYPE order by AUDITORIUM_CAPACITY desc)
--5
Select FACULTY_NAME from FACULTY
Where not exists (select* from PULPIT 
where PULPIT.FACULTY=FACULTY.FACULTY)
--6
Select top 1
(select avg(NOTE) from PROGRESS
where PROGRESS.SUBJECT like 'КГ')[КГ],
(select avg(NOTE) from PROGRESS
where PROGRESS.SUBJECT like 'СУБД')[СУБД],
(select avg(NOTE) from PROGRESS
where PROGRESS.SUBJECT like 'ОАиП')[ОАиП]
From PROGRESS
--7
SELECT A1.IDSTUDENT, A1.NOTE
FROM PROGRESS AS A1
WHERE A1.NOTE >= ALL(SELECT A2.NOTE 
FROM PROGRESS AS A2
WHERE A1.IDSTUDENT !=A2.IDSTUDENT);
--8
SELECT A1.IDSTUDENT, A1.NOTE
FROM PROGRESS AS A1
WHERE A1.NOTE >= ANY(SELECT A2.NOTE 
FROM PROGRESS AS A2
WHERE A1.IDSTUDENT!=A2.IDSTUDENT);
--10
SELECT DISTINCT S1.IDSTUDENT, S1.BDAY
FROM STUDENT AS S1
WHERE S1.BDAY = ANY (SELECT S2.BDAY FROM STUDENT AS S2
WHERE S1.IDSTUDENT!=S2.IDSTUDENT)
ORDER BY BDAY;
