use UNIVER;
select FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
From FACULTY inner join PULPIT
on PULPIT.FACULTY=FACULTY.FACULTY, PROFESSION
Where PULPIT.FACULTY=FACULTY.FACULTY AND FACULTY.FACULTY=PROFESSION.FACULTY
AND 
PROFESSION.PROFESSION_NAME IN(SELECT PROFESSION.PROFESSION_NAME
FROM PROFESSION
WHERE(PROFESSION.PROFESSION_NAME LIKE '%технология%'
or PROFESSION.PROFESSION_NAME LIKE '%технологии%'));