use UNIVER;
select FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
From FACULTY inner join PULPIT
on PULPIT.FACULTY=FACULTY.FACULTY
inner join PROFESSION on PROFESSION.FACULTY=FACULTY.FACULTY
WHERE(PROFESSION.PROFESSION_NAME LIKE '%технология%'
or PROFESSION.PROFESSION_NAME LIKE '%технологии%');