use UNIVER;
Select AUDITORIUM_CAPACITY, AUDITORIUM_TYPE
FROM AUDITORIUM as a
Where AUDITORIUM_CAPACITY=(select top(1) aa.AUDITORIUM_CAPACITY from AUDITORIUM as aa
where aa.AUDITORIUM_TYPE=a.AUDITORIUM_TYPE order by AUDITORIUM_CAPACITY desc)